export const employeeLeaveData = [
  {
    id: 1,
    fromDate: "05-Oct-2023",
    toDate: "05-Oct-2023",
    leaveType: "Half",
    typeColor: "yellow.600",
    statusColor: "green.600",
    leaveStatus: "Approved",
  },
  {
    id: 2,
    fromDate: "10-Nov-2023",
    toDate: "10-Nov-2023",
    leaveType: "Full",
    typeColor: "green.600",
    leaveStatus: "Pending",
    statusColor: "yellow.600",
  },
  {
    id: 3,
    fromDate: "15-Dec-2023",
    toDate: "16-Dec-2023",
    leaveType: "Full",
    typeColor: "green.600",
    leaveStatus: "Rejected",
    statusColor: "red.600",
  },
  {
    id: 4,
    fromDate: "20-Jan-2024",
    toDate: "22-Jan-2024",
    typeColor: "yellow.600",
    leaveType: "Half",
    statusColor: "green.600",
    leaveStatus: "Approved",
  },
  {
    id: 5,
    fromDate: "25-Feb-2024",
    toDate: "25-Feb-2024",
    leaveType: "Full",
    typeColor: "green.600",
    leaveStatus: "Pending",
    statusColor: "yellow.600",
  },
  {
    id: 6,
    fromDate: "30-Mar-2024",
    toDate: "01-Apr-2024",
    leaveType: "Full",
    typeColor: "green.600",
    statusColor: "green.600",
    leaveStatus: "Approved",
  },
  {
    id: 7,
    fromDate: "05-May-2024",
    toDate: "05-May-2024",
    typeColor: "yellow.600",
    leaveType: "Half",
    leaveStatus: "Rejected",
    statusColor: "red.600",
  },
  {
    id: 8,
    fromDate: "10-Jun-2024",
    toDate: "10-Jun-2024",
    leaveType: "Full",
    typeColor: "green.600",
    statusColor: "green.600",
    leaveStatus: "Approved",
  },
  {
    id: 9,
    fromDate: "15-Jul-2024",
    toDate: "16-Jul-2024",
    leaveType: "Full",
    typeColor: "green.600",
    leaveStatus: "Pending",
    statusColor: "yellow.600",
  },
  {
    id: 10,
    fromDate: "20-Aug-2024",
    toDate: "22-Aug-2024",
    typeColor: "yellow.600",
    leaveType: "Half",
    statusColor: "green.600",
    leaveStatus: "Approved",
  },
  {
    id: 11,
    fromDate: "25-Sep-2024",
    toDate: "25-Sep-2024",
    typeColor: "green.600",
    leaveType: "Full",
    leaveStatus: "Rejected",
    statusColor: "red.600",
  },
  {
    id: 12,
    fromDate: "30-Oct-2024",
    toDate: "01-Nov-2024",
    typeColor: "green.600",
    leaveType: "Full",
    statusColor: "green.600",
    leaveStatus: "Approved",
  },
  {
    id: 13,
    fromDate: "05-Nov-2024",
    toDate: "05-Nov-2024",
    typeColor: "yellow.600",
    leaveType: "Half",
    statusColor: "green.600",
    leaveStatus: "Approved",
  },
  {
    id: 14,
    fromDate: "10-Dec-2024",
    toDate: "10-Dec-2024",
    leaveType: "Full",
    typeColor: "green.600",
    leaveStatus: "Pending",
    statusColor: "yellow.600",
  },
  {
    id: 15,
    fromDate: "15-Jan-2025",
    toDate: "16-Jan-2025",
    leaveType: "Full",
    typeColor: "green.600",
    leaveStatus: "Rejected",
    statusColor: "red.600",
  },
  {
    id: 16,
    fromDate: "20-Feb-2025",
    toDate: "22-Feb-2025",
    typeColor: "yellow.600",
    leaveType: "Half",
    statusColor: "green.600",
    leaveStatus: "Approved",
  },
  {
    id: 17,
    fromDate: "25-Mar-2025",
    toDate: "25-Mar-2025",
    leaveType: "Full",
    typeColor: "green.600",
    leaveStatus: "Pending",
    statusColor: "yellow.600",
  },
  {
    id: 18,
    fromDate: "30-Apr-2025",
    toDate: "01-May-2025",
    leaveType: "Full",
    typeColor: "green.600",
    statusColor: "green.600",
    leaveStatus: "Approved",
  },
  {
    id: 19,
    fromDate: "05-May-2025",
    toDate: "05-May-2025",
    typeColor: "yellow.600",
    leaveType: "Half",
    leaveStatus: "Rejected",
    statusColor: "red.600",
  },
  {
    id: 20,
    fromDate: "10-Jun-2025",
    toDate: "10-Jun-2025",
    leaveType: "Full",
    typeColor: "green.600",
    statusColor: "green.600",
    leaveStatus: "Approved",
  },
  {
    id: 21,
    fromDate: "15-Jul-2025",
    toDate: "16-Jul-2025",
    leaveType: "Full",
    typeColor: "green.600",
    leaveStatus: "Pending",
    statusColor: "yellow.600",
  },
  {
    id: 22,
    fromDate: "20-Aug-2025",
    toDate: "22-Aug-2025",
    typeColor: "yellow.600",
    leaveType: "Half",
    statusColor: "green.600",
    leaveStatus: "Approved",
  },
  {
    id: 23,
    fromDate: "25-Sep-2025",
    toDate: "25-Sep-2025",
    leaveType: "Full",
    typeColor: "green.600",
    leaveStatus: "Rejected",
    statusColor: "red.600",
  },
  {
    id: 24,
    fromDate: "30-Oct-2025",
    toDate: "01-Nov-2025",
    leaveType: "Full",
    typeColor: "green.600",
    statusColor: "green.600",
    leaveStatus: "Approved",
  },
  {
    id: 25,
    fromDate: "05-Nov-2025",
    toDate: "05-Nov-2025",
    typeColor: "yellow.600",
    leaveType: "Half",
    statusColor: "green.600",
    leaveStatus: "Approved",
  },
  {
    id: 26,
    fromDate: "10-Dec-2025",
    toDate: "10-Dec-2025",
    leaveType: "Full",
    typeColor: "green.600",
    leaveStatus: "Pending",
    statusColor: "yellow.600",
  },
  {
    id: 27,
    fromDate: "15-Jan-2026",
    toDate: "16-Jan-2026",
    leaveType: "Full",
    typeColor: "green.600",
    leaveStatus: "Rejected",
    statusColor: "red.600",
  },
  {
    id: 28,
    fromDate: "20-Feb-2026",
    toDate: "22-Feb-2026",
    typeColor: "yellow.600",
    leaveType: "Half",
    statusColor: "green.600",
    leaveStatus: "Approved",
  },
  {
    id: 29,
    fromDate: "25-Mar-2026",
    toDate: "25-Mar-2026",
    leaveType: "Full",
    typeColor: "green.600",
    leaveStatus: "Pending",
    statusColor: "yellow.600",
  },
  {
    id: 30,
    fromDate: "30-Apr-2026",
    toDate: "01-May-2026",
    leaveType: "Full",
    typeColor: "green.600",
    statusColor: "green.600",
    leaveStatus: "Approved",
  },
  {
    id: 31,
    fromDate: "05-May-2026",
    toDate: "05-May-2026",
    typeColor: "yellow.600",
    leaveType: "Half",
    leaveStatus: "Rejected",
    statusColor: "red.600",
  },
  {
    id: 32,
    fromDate: "10-Jun-2026",
    toDate: "10-Jun-2026",
    leaveType: "Full",
    typeColor: "green.600",
    statusColor: "green.600",
    leaveStatus: "Approved",
  },
  {
    id: 33,
    fromDate: "15-Jul-2026",
    toDate: "16-Jul-2026",
    leaveType: "Full",
    typeColor: "green.600",
    leaveStatus: "Pending",
    statusColor: "yellow.600",
  },
  {
    id: 34,
    fromDate: "20-Aug-2026",
    toDate: "22-Aug-2026",
    typeColor: "yellow.600",
    leaveType: "Half",
    statusColor: "green.600",
    leaveStatus: "Approved",
  },
];

export const leavePolicyRules = [
  {
    id: 1,
    ruleDescription:
      " Types of Leave: Annual, Sick, Maternity/Paternity, Public Holidays, Unpaid.",
  },
  {
    id: 2,
    ruleDescription:
      "Request & Approval: Submit via system, supervisor approval.",
  },
  {
    id: 3,
    ruleDescription:
      " Carryover: Annual leave, limited. Sick leave, not accumulated.",
  },
  {
    id: 4,
    ruleDescription: " Documentation: Provide required proof.",
  },
  {
    id: 5,
    ruleDescription: "Leave Replacement: Ensure work coverage.",
  },
  {
    id: 6,
    ruleDescription: "Abuse: May lead to disciplinary action.",
  },
  {
    id: 7,
    ruleDescription: "Legal Compliance: Follow applicable laws.",
  },
  {
    id: 8,
    ruleDescription: "Review & Amendments: Subject to change.",
  },
  {
    id: 9,
    ruleDescription: "Contact HR: For questions or concerns.",
  },
];

export const leaveTypesList = [
  {
    id: "1",
    leaveType: "Vacation",
  },
  {
    id: "2",
    leaveType: "Sick Leave",
  },
  {
    id: "3",
    leaveType: "Personal Leave",
  },
  {
    id: "4",
    leaveType: "Maternity Leave",
  },
  {
    id: "5",
    leaveType: "Paternity Leave",
  },
];

export const leaveMenubar = [
  {
    id: "01",
    path: "/leaves",
    menuTittle: "LEAVE",
  },
  {
    id: "02",
    path: "/timesheet",
    menuTittle: "TIMESHEET",
  },
  {
    id: "03",
    path: "/attendance",
    menuTittle: "ATTENDANCE",
  },
  {
    id: "04",
    path: "/leave/performance",
    menuTittle: "PERFORMANCE",
  },
  {
    id: "05",
    path: "/leave/expenses-travel",
    menuTittle: "EXPENSES & TRAVEL",
  },
  {
    id: "06",
    path: "/leave/helpdesk",
    menuTittle: "HELPDESK",
  },
];

export const leaveApprover = ["Ankit Yadav", "Jhon Thomas", "Kevin Jhon"];
