export const assetInfo = [
  {
    id: "1",
    assetType: "Laptop",
    assetName: "Dell XPS 13",
    assetID: "DXPS13-001",
    assetCategory: "Electronics",
    assignedOn: "2023-01-15",
    acknowledgement: "Received",
    currentCondition: "Good",
  },
  {
    id: "2",
    assetType: "Desktop",
    assetName: "HP EliteDesk 800",
    assetID: "HPED800-002",
    assetCategory: "Electronics",
    assignedOn: "2023-02-03",
    acknowledgement: "Pending",
    currentCondition: "Fair",
  },
  {
    id: "3",
    assetType: "Monitor",
    assetName: "LG UltraGear 27GL83A-B",
    assetID: "LGUG27-003",
    assetCategory: "Electronics",
    assignedOn: "2023-03-10",
    acknowledgement: "Received",
    currentCondition: "Excellent",
  },
  {
    id: "4",
    assetType: "Chair",
    assetName: "Steelcase Gesture",
    assetID: "SG-004",
    assetCategory: "Furniture",
    assignedOn: "2023-04-21",
    acknowledgement: "Pending",
    currentCondition: "Good",
  },
  {
    id: "5",
    assetType: "Phone",
    assetName: "iPhone 13",
    assetID: "IP13-005",
    assetCategory: "Electronics",
    assignedOn: "2023-05-02",
    acknowledgement: "Received",
    currentCondition: "Excellent",
  },
  {
    id: "6",
    assetType: "Printer",
    assetName: "Epson EcoTank ET-4760",
    assetID: "ET4760-006",
    assetCategory: "Electronics",
    assignedOn: "2023-06-15",
    acknowledgement: "Pending",
    currentCondition: "Fair",
  },
  {
    id: "7",
    assetType: "Table",
    assetName: "IKEA LINNMON",
    assetID: "LINNMON-007",
    assetCategory: "Furniture",
    assignedOn: "2023-07-03",
    acknowledgement: "Received",
    currentCondition: "Good",
  },
  {
    id: "8",
    assetType: "Projector",
    assetName: "BenQ HT2050A",
    assetID: "BHT2050A-008",
    assetCategory: "Electronics",
    assignedOn: "2023-08-19",
    acknowledgement: "Pending",
    currentCondition: "Fair",
  },
  {
    id: "9",
    assetType: "Keyboard",
    assetName: "Logitech G Pro X",
    assetID: "LGPX-009",
    assetCategory: "Electronics",
    assignedOn: "2023-09-27",
    acknowledgement: "Received",
    currentCondition: "Good",
  },
  {
    id: "10",
    assetType: "Desk Lamp",
    assetName: "TaoTronics LED Desk Lamp",
    assetID: "TTLDL-010",
    assetCategory: "Electronics",
    assignedOn: "2023-10-05",
    acknowledgement: "Pending",
    currentCondition: "Excellent",
  },
];

export const assetInfoOne = [
  {
    id: "1",
    assetType: "Laptop",
    assetName: "Dell XPS 13",
    assetID: "DXPS13-001",
    assetCategory: "Electronics",
    assignedOn: "2023-01-15",
    acknowledgement: "Received",
    currentCondition: "Good",
  },
];

export const assetMenuList = [
  {
    id: "01",
    menuTittle: "Assigned Asset",
    menuPath: "/assets",
  },
  {
    id: "02",
    menuTittle: "Asset Request",
    menuPath: "/assets/asset-reuest",
  },
];
